### ISSUE TITLE
Cannot train voices

### ISSUE THREAD

**Issue by NickZNick033** [BenAAndrew/Voice-Cloning-App#10]
Using the latest windows installer, I've been able to upload audio clips and transcripts to construct a dataset and move up to the training portion of the software and it will start up but it just hangs and does not execute. I checked task manager and it's not using my GPU at all. It just doesn't start up.
Here is an screenshot of where it hangs:

![image](https://user-images.githubusercontent.com/64331177/112399675-a985b680-8cd4-11eb-9536-0f5264cda819.png)

I noticed that before training
![image](https://user-images.githubusercontent.com/64331177/112399107-9e7e5680-8cd3-11eb-8f29-4fabb2b5027d.png)
Dataset size has also been replaced from real numbers to NaN hours, NaN minutes, it should be around 50 minutes from 3 different clips after using the extend dataset function.

Attached is also a log of what the Voice Cloning App printed out while it was running.
[Voice Cloning App Log.txt](https://github.com/BenAAndrew/Voice-Cloning-App/files/6201164/Voice.Cloning.App.Log.txt)

**Comment by BenAAndrew** [comment]
@NickZNick033 Sorry for the late reply. It's very odd that it hangs and doesn't produce an error. 

If you have a look in the 'data' folder (which will be found in the same directory as the app) there should be a subfolder called 'datasets'. Inside of that should be a folder with the name of your dataset. When you find this folder could you check the following:

1. There is a file called 'metadata.csv' and a folder called 'wavs' inside the folder
2. The number of rows in 'metadata.csv' should equal the number of audio files in the 'wavs' folder

To be honest it's been a while since I've tested the dataset combiner and I will try it out myself tomorrow. I reckon something may have gone wrong during the dataset development which may explain the odd behaviour.

**Comment by BenAAndrew** [comment]
Closing as inactive and issue should have been fixed in recent release
