### ISSUE TITLE
TensorRT support - Denoiser support

### ISSUE THREAD

**Issue by AnasFX** [BenAAndrew/Voice-Cloning-App#110]
Hi, thanks for the great work .
Is is possible to add support for the NVIDIA TensorRT library, or the official PyTorch TensorRT library, as I have read it is suppose to be easy to implement and would give at least 6X times the learning performance and speed. 

There are also other interesting libraries like a replacement for Numpy from NVIDIA that is faster than Numpy it self.

Another question, is it possible to implement some kind of a denoiser for the generated voice, something like the Waveglow denoiser, cause that would really help to get decent results without the metallic or the noisy generated voices.

Thanks

**Comment by BenAAndrew** [comment]
Hi @AnasFX,

Thank you for the suggestions.

The implementation of tacotron2 with pytorch is a modified version taken from NVIDIA so I'm assuming it's the best option for the model but if you know otherwise please let me know.

I previously investigated denoisers but couldn't find any which really made a different. Do you know of any good ones?

**Comment by AnasFX** [comment]
Hi @BenAAndrew , unfortunately I don't know of one 😢 . I wish I knew . I am very thankful for your reply.
