### ISSUE TITLE
Using pretrained models

### ISSUE THREAD

**Issue by mellow-tnk** [BenAAndrew/Voice-Cloning-App#114]
Currently, training a new model from a dataset takes like 3000 to 5000 epochs, 10+ days, and several hours worth of audio data. But if you start with a pretrained model, you only need around 200 to 600 epochs, < 1 day, and 30 minutes of audio is enough to get a decent model.

**Comment by BenAAndrew** [comment]
Yes exactly, that's why the app supports uploading a pre-trained model.
- In local training, you can upload the pre-trained model on the training page (file upload underneath the dataset dropdown)
- In remote training, the NVIDIA pre-trained model is downloaded & used automatically. 

You can read more about training at https://benaandrew.github.io/Voice-Cloning-App/training/
